// Cities with official Methodist church presence in the 6th Ecclesiastical Region
// Source: Methodist Church of Brazil — 6th Region directory
export const METHODIST_CITIES_6TH_REGION: string[] = [
  "Americana",
  "Amparo",
  "Araçatuba",
  "Araraquara",
  "Araras",
  "Assis",
  "Atibaia",
  "Avaré",
  "Bauru",
  "Bebedouro",
  "Birigui",
  "Botucatu",
  "Bragança Paulista",
  "Cabreúva",
  "Caieiras",
  "Cajamar",
  "Campinas",
  "Campo Limpo Paulista",
  "Capivari",
  "Catanduva",
  "Cerquilho",
  "Cosmópolis",
  "Cruzeiro",
  "Diadema",
  "Franca",
  "Franco da Rocha",
  "Guaratinguetá",
  "Guarulhos",
  "Hortolândia",
  "Indaiatuba",
  "Iracemápolis",
  "Itanhaém",
  "Itapetininga",
  "Itapeva",
  "Itapira",
  "Itatiba",
  "Itu",
  "Jaboticabal",
  "Jacareí",
  "Jaguariúna",
  "Jales",
  "Jaú",
  "José Bonifácio",
  "Jundiaí",
  "Leme",
  "Limeira",
  "Lins",
  "Lorena",
  "Marília",
  "Matão",
  "Mauá",
  "Mirassol",
  "Mococa",
  "Mogi das Cruzes",
  "Mogi Guaçu",
  "Mogi Mirim",
  "Monte Mor",
  "Nova Odessa",
  "Osasco",
  "Ourinhos",
  "Paulínia",
  "Pedreira",
  "Penápolis",
  "Piedade",
  "Piracicaba",
  "Pirassununga",
  "Porto Feliz",
  "Presidente Prudente",
  "Registro",
  "Ribeirão Preto",
  "Rio Claro",
  "Salto",
  "Santa Bárbara d'Oeste",
  "Santa Rita do Passa Quatro",
  "Santo André",
  "Santos",
  "São Bernardo do Campo",
  "São Caetano do Sul",
  "São Carlos",
  "São João da Boa Vista",
  "São José do Rio Pardo",
  "São José do Rio Preto",
  "São José dos Campos",
  "São Paulo",
  "São Pedro",
  "São Roque",
  "São Vicente",
  "Sorocaba",
  "Sumaré",
  "Suzano",
  "Taboão da Serra",
  "Taquaritinga",
  "Tatui",
  "Taubaté",
  "Tupã",
  "Valinhos",
  "Vinhedo",
  "Votuporanga",
];

export const MINISTRY_FUNCTIONS = [
  "Seminarista",
  "Missionário(a) Designado(a)",
  "Aspirante",
  "Diácono(a)",
  "Presbítero(a)",
  "Pastor(a) Local",
  "Pastor(a) Distrital",
  "Superintendente Distrital",
  "Bispo(a)",
  "Evangelista",
  "Educador(a) Cristão(ã)",
  "Capelão(ã)",
  "Outro",
];
